### PR TITLE
Update tests to run on Django 1.8+.

### PR DESCRIPTION
**Pull request by YPCrumble**
Adds the new Django [`TEMPLATES` config](https://docs.djangoproject.com/en/1.10/ref/templates/upgrading/) to support Django 1.8+.

### CODE REVIEW

**Comment by YPCrumble** [comment]
@mishbahr sorry just saw this doesn't pass tests - I can't look right now but will come back later and figure out what went wrong.

**Comment by YPCrumble** [comment]
@mishbahr just updated the `tox.ini` to support Django 1.8+. All tests pass on my local machine. Would need to drop support for Django <= 1.8 and update TravisCI (if you're OK with this change).

Let me know what you think?

**Comment by mishbahr** [comment]
Can we update Travis config to use tox?

**Comment by YPCrumble** [comment]
@mishbahr good idea. I just updated `.travis.yml` to mirror `tox.ini` and tests passed - I'll come back later and see if I can configure travis to use `tox.ini`. I'm somewhat new to open source code so still getting the hang of TravisCI/tox. Thanks for your patience!

**Comment by YPCrumble** [comment]
@mishbahr I looked into using `tox.ini` to specify the build matrix for TravisCI. The issue is that this will only run one build per Python version on TravisCI rather than running one build per Python version and Django version. I think it's easier to use TravisCI with one test per element in the matrix, so I'm OK leaving the tests as they currently are. The drawback is that `tox.ini` and `.travis.yml` both need to specify the matrix, but I'd be OK with maintaining both configs.

Let me know if you'd prefer to simply run the `tox` script on TravisCI, or if you have another idea? Otherwise I think this PR is ready to go :).

**Comment by mishbahr** [comment]
I'll push it to PyPi as soon as I can.

**Pull request merged**
